server.port: 9010

spring:
  application:
    name: api-author

check.message: check status OK

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/
  instance:
      preferIpAddress: true