server.port: 8081

spring:
  application:
    name: service-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9002/eureka/

zuul:
  routes:
    api-author:
      path: /api-authors/**
